version: "3.8"

services:
  api:
    image: search_api
    container_name: search-api-service
    ports:
      - "8003:8003"
    environment:
      MS_BACKEND: milvus
      MS_MILVUS_URI: http://host.docker.internal:19530
      MS_MILVUS_COLLECTION_NAME: scenes
      MS_EMBEDDING_DIMENSION: "1024"
      MS_EMBEDDING_MODEL_NAME: BAAI/bge-m3
      MS_EMBEDDING_DEVICE: cuda
      MS_MONGO_URI: mongodb://host.docker.internal:27017/?replicaSet=rs0
      MS_MONGO_DB: Metadata_Enrichment
      MS_MONGO_COLLECTION: video_queue
    volumes:
      - C:\Users\Administrator\metadata_search:/app
    command: uvicorn api.main:app --host 0.0.0.0 --port 8003 --reload
    restart: unless-stopped
