name: md_search
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - accelerate==1.12.0
      - fastapi==0.128.6
      - uvicorn==0.40.0
      - pymilvus==2.6.8
      - pymilvus-model==0.3.2
      - pydantic-settings==2.12.0
      - pymongo==4.16.0
      - requests==2.32.5
      - sentence-transformers==5.2.2
      - transformers==5.1.0
      - tokenizers==0.22.2
      - safetensors==0.7.0
      - huggingface-hub>=1.4
      - torch==2.8.0
      - torchaudio==2.8.0
      - torchvision==0.25.0
      - python-multipart==0.0.6
