name: md_search
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2026.1.4=h4c7d964_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.12.12=py312hd8ed1ab_2
  - debugpy=1.8.20=py312ha1a9051_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.4=hd7fb8db_0
  - ipykernel=7.2.0=pyh6dadd2b_1
  - ipython=9.10.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - krb5=1.21.3=hdf4eb48_0
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.20=hc70643c_0
  - libzlib=1.3.1=h02ab6af_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.1=hf411b9b_1
  - packaging=25.0=py312haa95532_1
  - parso=0.8.6=pyhcf101f3_0
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.2=py312he5662c2_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.12.12=h716150d_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.12.12=hd8ed1ab_2
  - python_abi=3.12=3_cp312
  - pywin32=311=py312h829343e_1
  - pyzmq=27.1.0=py312hbb5da91_0
  - setuptools=80.10.2=py312haa95532_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.1=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=hf199647_0
  - tornado=6.5.4=py312he06e257_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.6.0=pyhd8ed1ab_0
  - wheel=0.46.3=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h5bddc39_9
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - accelerate==1.12.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.1
      - boto3==1.42.45
      - botocore==1.42.45
      - bson==0.5.10
      - cachetools==7.0.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - deprecated==1.3.1
      - dnspython==2.8.0
      - events==0.5
      - fastapi==0.128.6
      - filelock==3.20.3
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - fsspec==2026.2.0
      - grpcio==1.78.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.4.1
      - idna==3.11
      - jinja2==3.1.6
      - jmespath==1.1.0
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.6.1
      - numpy==2.4.2
      - onnxruntime==1.24.1
      - opensearch-protobufs==0.19.0
      - opensearch-py==3.1.0
      - opensearch-py-ml==1.3.0
      - orjson==3.11.7
      - pandas==2.2.3
      - pillow==12.1.0
      - protobuf==6.33.5
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pymilvus==2.6.8
      - pymilvus-model==0.3.2
      - pymongo==4.16.0
      - pyparsing==3.3.2
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2026.1.15
      - requests==2.32.5
      - requests-aws4auth==1.3.1
      - rich==14.3.2
      - s3transfer==0.16.0
      - safetensors==0.7.0
      - scikit-learn==1.8.0
      - scipy==1.17.0
      - sentence-transformers==5.2.2
      - shellingham==1.5.4
      - starlette==0.52.1
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.22.2
      - torch==2.8.0+cu129
      - torchaudio==2.8.0+cu129
      - torchvision==0.23.0+cu129
      - tqdm==4.67.3
      - transformers==5.1.0
      - typer-slim==0.21.1
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.3
      - uvicorn==0.40.0
      - wrapt==2.1.1
prefix: C:\Users\leduc\miniconda3\envs\md_search
